#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>

#include "doom_input_queue.h"
#include "doom_frame_capture.h"

// Embeds the WAD bytes (doom_wad, doom_wad_len) into this translation unit.
// Generated by tools/embed_wad.sh and consumed by the DOOMWAD_FROM_MEMORY
// path in doomgeneric/w_file_stdc.c.
#include "wad_embedded.h"

// wasi libc has no system(3); doomgeneric's I_Error path calls it to spawn
// a shell. Returning -1 is the documented "shell unavailable" behavior.
int system(const char *command) {
    (void)command;
    return -1;
}

extern unsigned char *DG_ScreenBuffer;    // doomgeneric.c, type depends on CMAP256

// Monotonic millisecond counter advanced by the transform entry point.
// Doom mostly uses this for UI timing; the game sim is tic-locked, so
// coarse ticks are fine.
static uint32_t s_ticks_ms;

void doom_stubs_advance_ticks(uint32_t delta_ms) {
    s_ticks_ms += delta_ms;
}

void DG_Init(void) {
    // Force unbuffered stdout/stderr so any crash-adjacent printf output
    // actually reaches the transform log topic instead of dying in a
    // libc buffer on WASI trap.
    setvbuf(stdout, NULL, _IONBF, 0);
    setvbuf(stderr, NULL, _IONBF, 0);
}

void DG_DrawFrame(void) {
    // DG_ScreenBuffer is 64000 bytes when built with -DCMAP256=1
    // and DOOMGENERIC_RESX/Y = 320/200.
    doom_frame_capture_on_draw((const uint8_t *)DG_ScreenBuffer);
}

uint32_t DG_GetTicksMs(void) {
    // Auto-advance on each call so Doom's internal spin loops (e.g.
    // TryRunTics's "wait for new tics" loop during D_DoomMain init)
    // always observe forward progress. Without this, I_GetTime stays
    // at 0 throughout D_DoomMain and TryRunTics spins forever, causing
    // the WASM host to kill the transform for exceeding its per-record
    // deadline. The real advance_ticks hook below still runs each tick
    // so the per-record tic rate stays tied to record count.
    s_ticks_ms++;
    return s_ticks_ms;
}

void DG_SleepMs(uint32_t ms) {
    // In a transform there is no wall clock to sleep against.
    // Swallow — Doom only sleeps when idle, and it'll be fine.
    (void)ms;
}

int DG_GetKey(int *pressed, unsigned char *doom_key) {
    return doom_input_queue_pop(pressed, doom_key);
}

void DG_SetWindowTitle(const char *title) {
    (void)title;
}
